[package]
name = "ldap"
version = "0.0.4"
authors = [ "Dean Davis <dean4devil@chaingamers.com>" ]

description = "Pure Rust LDAP Client"
repository = "https://github.com/dean4devil/rust-ldap"
readme = "README.md"

keywords = ["ldap", "libldap"]

license = "MIT"

[dependencies]
byteorder = "*"
